# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupsIn3D' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GroupsIn3D
  pod 'ProjectOxfordFace'
  pod 'ADAL', '~> 2.2'
  
  target 'GroupsIn3DTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupsIn3DUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
